import { HeaderBrand } from "@/components/HeaderBrand";
import { PRODUCT_CONTACT_EMAIL } from "@/lib/product";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service: Upside Lab",
};

export default function TermsPage() {
  return (
    <div className="min-h-dvh bg-[radial-gradient(ellipse_at_top,_#161b25_0%,_#08090c_55%)] text-foreground">
      <header className="border-b border-border bg-app/90 backdrop-blur">
        <div className="mx-auto flex max-w-3xl items-center justify-between gap-3 px-4 py-3">
          <HeaderBrand />
          <Link
            href="/"
            className="rounded-md border border-border px-2.5 py-1.5 text-sm text-muted hover:border-brand hover:text-foreground"
          >
            Back
          </Link>
        </div>
      </header>

      <main id="main" className="mx-auto min-w-0 max-w-3xl space-y-6 px-4 py-10 text-sm leading-relaxed text-foreground/80">
        <div>
          <h1 className="text-lg font-bold text-foreground">Terms of Service</h1>
          <p className="mt-1 text-sm text-muted">Last updated {LAST_UPDATED}</p>
        </div>

        <p>
          These terms cover your use of Upside Lab (&ldquo;the app,&rdquo;
          &ldquo;we,&rdquo; &ldquo;us&rdquo;). By creating an account or
          signing in, you agree to them.
        </p>

        <Section title="1. Not financial advice">
          Upside Lab is a tracking and planning tool. Numbers, targets, forecasts,
          and anything generated by the AI assistant (&ldquo;Margus&rdquo;) or
          other AI features are informational only, not investment,
          financial, tax, or legal advice, and not a recommendation to buy,
          sell, or hold any security or to write any option contract. You are
          solely responsible for your own investment decisions. Markets carry
          real risk of loss, including total loss of principal; options
          strategies (including covered calls) carry additional, specific
          risks. Consult a licensed professional before acting on anything
          you see here.
        </Section>

        <Section title="2. Your account">
          You sign in with Google. You&apos;re responsible for keeping that
          Google account secure. Anyone with access to it can access your
          Upside Lab data. You must be old enough in your jurisdiction to enter a
          binding agreement to use the app.
        </Section>

        <Section title="3. Your data, your entries">
          You keep ownership of the portfolio data you enter (holdings, cash,
          notes, targets). You&apos;re responsible for its accuracy; we
          don&apos;t verify anything you type in. If you invite a co-owner to
          a sheet or join a community/leaderboard, you&apos;re choosing to
          share that sheet&apos;s data (or a limited read-only summary, for
          communities) with the people you invite or who share that
          community. Don&apos;t enter data you don&apos;t have the right to
          share with the people you invite.
        </Section>

        <Section title="4. Market data & third parties">
          Prices, quotes, options chains, earnings dates, and seasonality
          stats come from third-party data providers on a best-effort,
          &ldquo;as available&rdquo; basis. Data can be delayed, incomplete,
          synthetic (estimated when a live feed is unavailable), or wrong. We
          flag desynced or estimated data where we can detect it, but we make
          no accuracy or availability guarantee. AI features call third-party
          model providers; if every provider is temporarily unavailable, that
          feature degrades or fails rather than the rest of the app.
        </Section>

        <Section title="5. Acceptable use">
          Don&apos;t attempt to break, scrape at abusive volume, reverse
          engineer for competitive cloning, or use the app to store data you
          don&apos;t have rights to. Don&apos;t use it to provide financial
          advice to third parties under our name. We may suspend accounts
          that abuse shared infrastructure (for example, hammering the AI or
          market-data endpoints in a way that degrades service for others).
        </Section>

        <Section title="6. Availability">
          This is a small, evolving product. We don&apos;t guarantee uptime,
          and features can change, be renamed, or be removed as the app
          develops. We take reasonable care with backups but you can export
          your own data at any time from{" "}
          <Link href="/account" className="underline hover:text-foreground">
            My account
          </Link>
          , so please don&apos;t treat Upside Lab as your only record of anything
          important.
        </Section>

        <Section title="7. Liability">
          Upside Lab is provided &ldquo;as is,&rdquo; without warranties of any
          kind. To the maximum extent permitted by law, we aren&apos;t liable
          for trading losses, missed gains, data loss, or any decision made
          using information from the app.
        </Section>

        <Section title="8. Changes">
          We may update these terms as the product changes. Material changes
          will be reflected here with a new &ldquo;last updated&rdquo; date.
          Continuing to use Upside Lab after a change means you accept the
          update.
        </Section>

        <Section title="9. Contact">
          Questions about these terms:{" "}
          <a
            href={`mailto:${PRODUCT_CONTACT_EMAIL}`}
            className="underline hover:text-foreground"
          >
            {PRODUCT_CONTACT_EMAIL}
          </a>
          .
        </Section>

        <p className="pt-4 text-sm text-muted">
          See also our{" "}
          <Link href="/privacy" className="underline hover:text-foreground">
            Privacy policy
          </Link>
          .
        </p>
      </main>
    </div>
  );
}

const LAST_UPDATED = "August 2026";

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-2">
      <h2 className="text-sm font-semibold text-foreground">{title}</h2>
      <p>{children}</p>
    </section>
  );
}
