import { HeaderBrand } from "@/components/HeaderBrand";
import { Button } from "@/components/ui/button";
import {
  LEGAL_ADDRESS,
  LEGAL_COUNTRY,
  LEGAL_OPERATOR,
  LEGAL_REGISTRY_CODE,
  LEGAL_VAT_ID,
  PRODUCT_CONTACT_EMAIL,
  PRODUCT_NAME,
} from "@/lib/product";
import Link from "next/link";
import { publicPageMetadata } from "@/lib/site-metadata";
import type { ReactNode } from "react";

export const metadata = publicPageMetadata({
  title: "Terms of Service",
  description: "The rules for using Upside Lab.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <div className="min-h-dvh bg-background text-foreground">
      <header className="border-b border-border bg-background/90 backdrop-blur">
        <div className="mx-auto flex max-w-3xl items-center justify-between gap-3 px-4 py-3">
          <HeaderBrand />
          <Button asChild variant="outline" size="sm">
            <Link href="/">Back</Link>
          </Button>
        </div>
      </header>

      <main id="main" className="flex flex-col mx-auto min-w-0 max-w-3xl gap-6 px-6 py-10 text-sm leading-relaxed text-foreground">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight text-foreground">Terms of Service</h1>
          <p className="mt-1 text-sm text-muted-foreground">Last updated {LAST_UPDATED}</p>
        </div>

        <p>
          These terms cover your use of {PRODUCT_NAME} (&ldquo;the app,&rdquo;
          &ldquo;we,&rdquo; &ldquo;us&rdquo;). By creating an account or
          signing in, you agree to them.
        </p>

        <Section title="1. Who we are">
          {PRODUCT_NAME} is operated by {LEGAL_OPERATOR}, a private limited
          company in {LEGAL_COUNTRY} (registry code {LEGAL_REGISTRY_CODE}).
          Registered office: {LEGAL_ADDRESS}. VAT ID {LEGAL_VAT_ID}. Questions:{" "}
          <a
            href={`mailto:${PRODUCT_CONTACT_EMAIL}`}
            className="underline hover:text-foreground"
          >
            {PRODUCT_CONTACT_EMAIL}
          </a>
          .
        </Section>

        <Section title="2. Not financial advice">
          {PRODUCT_NAME} is a tracking and planning tool. Numbers, targets, forecasts,
          and anything generated by the AI assistant (&ldquo;Margus&rdquo;) or
          other AI features are informational only, not investment,
          financial, tax, or legal advice, and not a recommendation to buy,
          sell, or hold any security or to write any option contract. You are
          solely responsible for your own investment decisions. Markets carry
          real risk of loss, including total loss of principal; options
          strategies (including covered calls) carry additional, specific
          risks. Consult a licensed professional before acting on anything
          you see here.
        </Section>

        <Section title="3. Your account">
          You sign in with Google. You&apos;re responsible for keeping that
          Google account secure. Anyone with access to it can access your{" "}
          {PRODUCT_NAME} data. Under 13 is never allowed. Classroom is a
          teacher-invite paper class (see below), not a brokerage.
        </Section>

        <Section title="4. Classroom">
          A teacher can invite a class into a private paper Classroom. Each
          student gets homework cash and an empty sheet. It is not a real
          brokerage, not real money, and not a real book. Real sheets cannot
          be shared into a class. The teacher sets when buying and selling
          are allowed. If you are a student, you join only with that invite.
          If your country needs a parent or guardian for someone your age to
          use an app like this, that person has to agree. The teacher is
          responsible for running the class under their school&apos;s rules.
        </Section>

        <Section title="5. Your data, your entries">
          You keep ownership of the portfolio data you enter (holdings, cash,
          notes, thesis text). You&apos;re responsible for its accuracy; we
          don&apos;t verify anything you type in. If you invite a co-owner to
          a sheet, they can read and edit everything on that sheet. If you
          join a circle, members can see today&apos;s prices, the names you
          hold, cash, and returns for the sheets you linked. They do not see
          what you paid unless you also made them a co-owner. If two
          accounts are linked as a household, Circle join, leave, and role
          copy to both. Classroom stays per person. Don&apos;t enter data you
          don&apos;t have the right to share with those people.
        </Section>

        <Section title="6. Market data and third parties">
          Prices, quotes, options chains, earnings dates, and seasonality
          stats come from third-party data providers on a best-effort,
          &ldquo;as available&rdquo; basis. We do not run a licensed
          exchange feed. Data can be delayed, incomplete, estimated when a
          live feed is unavailable, or wrong. We flag desynced or estimated
          data where we can detect it, but we make no accuracy or
          availability guarantee. AI features call third-party model
          providers. Some of those providers process data outside{" "}
          {LEGAL_COUNTRY}, including the United States. If every provider is
          temporarily unavailable, that feature degrades or fails rather than
          the rest of the app.
        </Section>

        <Section title="7. Acceptable use">
          Don&apos;t attempt to break, scrape at abusive volume, reverse
          engineer for competitive cloning, or use the app to store data you
          don&apos;t have rights to. Don&apos;t use it to provide financial
          advice to third parties under our name. We may suspend accounts
          that abuse shared infrastructure (for example, hammering the AI or
          market-data endpoints in a way that degrades service for others).
        </Section>

        <Section title="8. Availability">
          This is a small, evolving product. We don&apos;t guarantee uptime,
          and features can change, be renamed, or be removed as the app
          develops. We take reasonable care with backups but you can export
          your own data at any time from{" "}
          <Link href="/account" className="underline hover:text-foreground">
            My account
          </Link>
          , so please don&apos;t treat {PRODUCT_NAME} as your only record of
          anything important.
        </Section>

        <Section title="9. Liability">
          {PRODUCT_NAME} is provided &ldquo;as is,&rdquo; without warranties of
          any kind, except where the law of {LEGAL_COUNTRY} or your EU
          consumer rights say we cannot disclaim them. To the maximum extent
          permitted by law, we aren&apos;t liable for trading losses, missed
          gains, data loss, or any decision made using information from the
          app. If you are an EU consumer, you keep the mandatory protections
          of your home country.
        </Section>

        <Section title="10. Governing law">
          These terms are governed by the laws of {LEGAL_COUNTRY}. Courts in{" "}
          {LEGAL_COUNTRY} have jurisdiction, except that EU consumers may
          also bring a claim in their home country where the law gives them
          that right.
        </Section>

        <Section title="11. Changes">
          We may update these terms as the product changes. Material changes
          will be reflected here with a new &ldquo;last updated&rdquo; date.
          Continuing to use {PRODUCT_NAME} after a change means you accept the
          update.
        </Section>

        <Section title="12. Contact">
          Questions about these terms:{" "}
          <a
            href={`mailto:${PRODUCT_CONTACT_EMAIL}`}
            className="underline hover:text-foreground"
          >
            {PRODUCT_CONTACT_EMAIL}
          </a>
          .
        </Section>

        <p className="pt-4 text-sm text-muted-foreground">
          See also our{" "}
          <Link href="/privacy" className="underline hover:text-foreground">
            Privacy policy
          </Link>
          .
        </p>
      </main>
    </div>
  );
}

const LAST_UPDATED = "17 August 2026";

function Section({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section className="flex flex-col gap-2">
      <h2 className="text-sm font-semibold text-foreground">{title}</h2>
      <p>{children}</p>
    </section>
  );
}
